mindmap
  root((stuff))
    AI
        claude code
            agents
        8090
        funcionaliades
            pesquisa em Natural language
            text to speach
            winml
    Cripto
        fundamentals
        blockchain para registos
        contratos para mudança de estados
        solidity
    PM
        product owner cert
        criar user stories
    DEV
        Mobile App
            react native
                expo
                bare
            mcp para google console
        Web App
            react
            playwright
        Backend
            aspire
                open telemetry
            minimal api
            unit test
            archtest
        CI/CD
            github actions
            local
            azure
        docker
            test container
            deploy container
        
